package io.github.aedev.flow.ui.screens.player.state

import io.github.aedev.flow.player.EnhancedPlayerManager
import io.github.aedev.flow.player.state.SubtitleOption
import io.github.aedev.flow.player.stream.CaptionTrackResolver

internal object SubtitleSelection {
    fun indexOfLanguage(
        subtitles: List<SubtitleOption>,
        languageTag: String?,
    ): Int {
        val match =
            CaptionTrackResolver.bestMatch(
                candidates = subtitles,
                languageTag = languageTag,
                tagOf = { it.language },
                isAutoGenerated = { it.isAutoGenerated || it.isTranslated },
            ) ?: return -1
        return subtitles.indexOf(match)
    }

    /** Index to fall back on when nothing is remembered: a human-authored track if there is one. */
    private fun defaultIndex(subtitles: List<SubtitleOption>): Int =
        subtitles
            .indexOfFirst { !it.isAutoGenerated && !it.isTranslated }
            .takeIf { it >= 0 }
            ?: subtitles.indices.firstOrNull() ?: -1

    fun applyAt(
        screenState: PlayerScreenState,
        subtitles: List<SubtitleOption>,
        index: Int,
        rememberLanguage: (String) -> Unit,
    ): Boolean {
        val subtitle = subtitles.getOrNull(index) ?: return false
        EnhancedPlayerManager.getInstance().selectSubtitle(index)
        screenState.enableSubtitles(subtitle.url)
        subtitle.language.takeIf { it.isNotBlank() }?.let(rememberLanguage)
        return true
    }

    fun enable(
        screenState: PlayerScreenState,
        subtitles: List<SubtitleOption>,
        languageTag: String?,
        rememberLanguage: (String) -> Unit,
    ): Boolean {
        if (subtitles.isEmpty()) return false
        val index = indexOfLanguage(subtitles, languageTag).takeIf { it >= 0 } ?: defaultIndex(subtitles)
        return applyAt(screenState, subtitles, index, rememberLanguage)
    }

    /**
     * The track to drop to when [failedIndex] gave up, or null when nothing is worth trying.
     *
     * Only a translation falls back: it is a machine pass over a track that is usually still
     * loadable, so the same language authored or auto-generated is the closest thing to what the
     * user asked for, and any untranslated track beats switching subtitles off.
     */
    fun fallbackIndexFor(
        subtitles: List<SubtitleOption>,
        failedIndex: Int,
        failedLanguage: String?,
        wasTranslated: Boolean,
    ): Int? {
        if (!wasTranslated) return null
        val candidates =
            subtitles.withIndex().filter { (index, option) ->
                index != failedIndex && !option.isTranslated
            }
        if (candidates.isEmpty()) return null
        val sameLanguage =
            failedLanguage?.let { wanted ->
                CaptionTrackResolver.bestMatch(
                    candidates = candidates,
                    languageTag = wanted,
                    tagOf = { it.value.language },
                    isAutoGenerated = { it.value.isAutoGenerated },
                )
            }
        return (sameLanguage ?: candidates.firstOrNull { !it.value.isAutoGenerated } ?: candidates.first()).index
    }

    fun disable(screenState: PlayerScreenState) {
        EnhancedPlayerManager.getInstance().selectSubtitle(null)
        screenState.disableSubtitles()
    }
}
