# These are supported funding model platforms

github: # Leave empty
patreon: # Leave empty
open_collective: # Leave empty
ko_fi: # Leave empty
tidelift: # Leave empty
community_bridge: # Leave empty
liberapay: # Leave empty
issuehunt: # Leave empty
lfx_crowdfunding: # Leave empty
polar: # Leave empty
buy_me_a_coffee: # Leave empty
thanks_dev: # Leave empty

# Link directly to the "Support & Donations" section of your README
custom: ["https://github.com/A-EDev/Flow#support--donations"]
