package io.github.aedev.flow.data.localmedia

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.provider.OpenableColumns
import android.util.Log
import dagger.hilt.android.qualifiers.ApplicationContext
import io.github.aedev.flow.player.stream.CaptionFormat
import io.github.aedev.flow.player.stream.CaptionSource
import io.github.aedev.flow.player.stream.ResolvedCaption
import io.github.aedev.flow.utils.PerformanceDispatcher
import kotlinx.coroutines.withContext
import java.io.File
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Subtitle files for videos on the device: the ones beside a video, and the ones someone picked
 * for it. MediaStore indexes subtitle files like `.lrc` lyrics, so the video permission that lists
 * a video lets Flow read the files next to it. Nothing here touches the network.
 */
@Singleton
class LocalSubtitles
    @Inject
    constructor(
        @param:ApplicationContext private val context: Context,
        private val picks: PickedSubtitleStore,
    ) {
        /** The subtitle files beside the video at [videoPath], a content Uri or a file path. */
        suspend fun beside(videoPath: String): List<ResolvedCaption> =
            withContext(PerformanceDispatcher.diskIO) {
                val video = fileOf(videoPath) ?: return@withContext emptyList()
                val folder = video.parentFile ?: return@withContext emptyList()
                val names = runCatching { folder.list()?.toList() }.getOrNull().orEmpty()
                matchingSubtitleFiles(video.name, names).mapNotNull { match ->
                    val file = File(folder, match.name)
                    readableUrl(Uri.fromFile(file), match.format)?.let { url ->
                        ResolvedCaption(
                            match.languageTag,
                            isAutoGenerated = false,
                            url = url,
                            format = match.format,
                            label = match.name,
                            source = CaptionSource.SIDECAR,
                        )
                    }
                }
            }

        /** The subtitle files picked for [videoId] that can still be read. */
        suspend fun picked(videoId: String): List<ResolvedCaption> =
            withContext(PerformanceDispatcher.diskIO) {
                picks.forVideo(videoId).mapNotNull { pick -> pickedCaption(Uri.parse(pick.uri), pick.name) }
            }

        /** Remembers [uri] for [videoId]; null when it is not a subtitle file Flow can read. */
        suspend fun pick(
            videoId: String,
            uri: Uri,
        ): ResolvedCaption? =
            withContext(PerformanceDispatcher.diskIO) {
                val name = displayName(uri) ?: return@withContext null
                val caption = pickedCaption(uri, name) ?: return@withContext null
                runCatching { context.contentResolver.takePersistableUriPermission(uri, Intent.FLAG_GRANT_READ_URI_PERMISSION) }
                    .onFailure { Log.w(TAG, "No lasting read access to $name", it) }
                picks.add(videoId, PickedSubtitle(uri.toString(), name))
                caption
            }

        private fun pickedCaption(
            uri: Uri,
            name: String,
        ): ResolvedCaption? {
            val format = CaptionFormat.ofExtension(name.substringAfterLast('.', "")) ?: return null
            val url = readableUrl(uri, format) ?: return null
            val language = subtitleLanguageOf(name.substringBeforeLast('.').split('.').drop(1))
            return ResolvedCaption(
                language,
                isAutoGenerated = false,
                url = url,
                format = format,
                label = name,
                source = CaptionSource.PICKED,
            )
        }

        /**
         * A URL the player can read [uri] from. Media3 reads subtitles as UTF-8 unless they start
         * with a byte-order mark, so a file in an older code page is decoded and copied to the cache.
         */
        private fun readableUrl(
            uri: Uri,
            format: CaptionFormat,
        ): String? =
            try {
                val bytes =
                    context.contentResolver.openInputStream(uri)?.use { input ->
                        input.readAtMost(MAX_SUBTITLE_BYTES)
                    } ?: return null
                when {
                    bytes.size > MAX_SUBTITLE_BYTES -> {
                        null
                    }

                    isUnicodeText(bytes) -> {
                        uri.toString()
                    }

                    else -> {
                        val text = decodeTextFile(bytes) { legacyTextCharset(Locale.getDefault()) }
                        val copy =
                            File(
                                File(context.cacheDir, CACHE_DIR).apply { mkdirs() },
                                "${uri.toString().hashCode().toUInt()}.${format.name.lowercase(Locale.ROOT)}",
                            )
                        copy.writeText(text)
                        Uri.fromFile(copy).toString()
                    }
                }
            } catch (e: Exception) {
                Log.w(TAG, "Could not read the subtitle file $uri: ${e.message}")
                null
            }

        private fun fileOf(videoPath: String): File? {
            val uri = Uri.parse(videoPath)
            val path =
                when (uri.scheme) {
                    "content" -> context.mediaStoreDataPath(uri)
                    "file" -> uri.path
                    else -> videoPath.takeIf { it.startsWith("/") }
                }
            return path?.let(::File)
        }

        private fun displayName(uri: Uri): String? =
            runCatching {
                context.contentResolver.query(uri, arrayOf(OpenableColumns.DISPLAY_NAME), null, null, null)?.use { cursor ->
                    if (cursor.moveToFirst()) cursor.getString(0) else null
                }
            }.getOrNull() ?: uri.lastPathSegment?.substringAfterLast('/')

        private companion object {
            const val TAG = "LocalSubtitles"
            const val CACHE_DIR = "subtitles"
            const val MAX_SUBTITLE_BYTES = 8 * 1024 * 1024
        }
    }
