package io.github.aedev.flow.ui.screens.player.state

import com.google.common.truth.Truth.assertThat
import io.github.aedev.flow.player.state.SubtitleOption
import org.junit.Test

private fun option(
    language: String,
    isAutoGenerated: Boolean = false,
    isTranslated: Boolean = false,
) = SubtitleOption(
    url = "https://example.test/$language${if (isTranslated) "&tlang=$language" else ""}",
    language = language,
    label = language,
    isAutoGenerated = isAutoGenerated,
    isTranslated = isTranslated,
)

class SubtitleFallbackTest {
    @Test
    fun `an authored track that fails has no fallback`() {
        val subtitles = listOf(option("en"), option("fr"))

        val fallback =
            SubtitleSelection.fallbackIndexFor(subtitles, failedIndex = 0, failedLanguage = "en", wasTranslated = false)

        assertThat(fallback).isNull()
    }

    @Test
    fun `a failed translation prefers the same language authored track`() {
        val subtitles = listOf(option("en"), option("es"), option("es", isTranslated = true))

        val fallback =
            SubtitleSelection.fallbackIndexFor(subtitles, failedIndex = 2, failedLanguage = "es", wasTranslated = true)

        assertThat(fallback).isEqualTo(1)
    }

    @Test
    fun `a failed translation falls back to an authored track in another language`() {
        val subtitles = listOf(option("en"), option("ja", isTranslated = true))

        val fallback =
            SubtitleSelection.fallbackIndexFor(subtitles, failedIndex = 1, failedLanguage = "ja", wasTranslated = true)

        assertThat(fallback).isEqualTo(0)
    }

    @Test
    fun `an auto-generated track is used only when nothing authored remains`() {
        val subtitles = listOf(option("en", isAutoGenerated = true), option("ja", isTranslated = true))

        val fallback =
            SubtitleSelection.fallbackIndexFor(subtitles, failedIndex = 1, failedLanguage = "ja", wasTranslated = true)

        assertThat(fallback).isEqualTo(0)
    }

    @Test
    fun `a translation is never the fallback for another translation`() {
        val subtitles = listOf(option("fr", isTranslated = true), option("ja", isTranslated = true))

        val fallback =
            SubtitleSelection.fallbackIndexFor(subtitles, failedIndex = 1, failedLanguage = "ja", wasTranslated = true)

        assertThat(fallback).isNull()
    }

    @Test
    fun `the failed track is never its own fallback`() {
        val subtitles = listOf(option("ja", isTranslated = true))

        val fallback =
            SubtitleSelection.fallbackIndexFor(subtitles, failedIndex = 0, failedLanguage = "ja", wasTranslated = true)

        assertThat(fallback).isNull()
    }
}
