package io.github.aedev.flow.player.stream

import android.util.Log
import io.github.aedev.flow.innertube.models.response.PlayerResponse
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import java.util.Locale

object CaptionTrackResolver {
    private const val TAG = "CaptionTrackResolver"

    /** Marks a track produced by YouTube's machine translation of another caption track. */
    const val TRANSLATED_PARAM = "tlang"

    const val NO_PREFERRED_LANGUAGE = "none"

    fun resolve(playerResponse: PlayerResponse): List<SubtitlesStream> =
        resolveTracklist(playerResponse.captions?.playerCaptionsTracklistRenderer)

    fun resolveTracklist(renderer: PlayerResponse.Captions.PlayerCaptionsTracklistRenderer?): List<SubtitlesStream> {
        if (renderer == null) return emptyList()
        val tracks =
            renderer.captionTracks
                ?.filter { !it.baseUrl.isNullOrBlank() && !it.languageCode.isNullOrBlank() }
                .orEmpty()
        if (tracks.isEmpty()) return emptyList()

        val result =
            tracks.mapNotNull { track ->
                buildStream(track.baseUrl!!, track.languageCode!!, autoGenerated = track.kind == "asr")
            }

        Log.d(TAG, "Resolved ${result.size} caption tracks from InnerTube captions")
        return result
    }

    fun isTranslated(stream: SubtitlesStream): Boolean = stream.getContent().contains("&$TRANSLATED_PARAM=")

    private fun buildStream(
        baseUrl: String,
        languageCode: String,
        autoGenerated: Boolean,
    ): SubtitlesStream? =
        try {
            SubtitlesStream
                .Builder()
                .setContent(timedTextUrl(baseUrl), true)
                .setMediaFormat(MediaFormat.VTT)
                .setLanguageCode(languageCode)
                .setAutoGenerated(autoGenerated)
                .build()
        } catch (e: Exception) {
            Log.w(TAG, "Failed to build SubtitlesStream for $languageCode: ${e.message}")
            null
        }

    private fun timedTextUrl(baseUrl: String): String {
        val separatorIndex = baseUrl.indexOf('?')
        val path = if (separatorIndex >= 0) baseUrl.substring(0, separatorIndex) else baseUrl
        val query = if (separatorIndex >= 0) baseUrl.substring(separatorIndex + 1) else ""

        val retained =
            query
                .split('&')
                .filter { it.isNotEmpty() && !it.isParam("fmt") && !it.isParam(TRANSLATED_PARAM) }
                .toMutableList()

        retained.add("fmt=vtt")

        return "$path?${retained.joinToString("&")}"
    }

    private fun String.isParam(name: String): Boolean = startsWith("$name=", ignoreCase = true) || equals(name, ignoreCase = true)

    fun <T> bestMatch(
        candidates: List<T>,
        languageTag: String?,
        tagOf: (T) -> String?,
        isAutoGenerated: (T) -> Boolean,
    ): T? {
        val wanted = languageTag?.takeIf { it.isNotBlank() && it != NO_PREFERRED_LANGUAGE } ?: return null
        val wantedBase = baseLanguage(wanted)
        val ranked =
            candidates
                .filter { baseLanguage(tagOf(it).orEmpty()) == wantedBase }
                .sortedWith(
                    compareBy<T> { !tagOf(it).equals(wanted, ignoreCase = true) }
                        .thenBy { isAutoGenerated(it) },
                )
        return ranked.firstOrNull()
    }

    private fun baseLanguage(tag: String): String =
        tag
            .substringBefore('-')
            .substringBefore('_')
            .lowercase(Locale.ROOT)
}
