package io.github.aedev.flow.player.stream

import android.util.Log
import io.github.aedev.flow.innertube.models.response.PlayerResponse
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import java.util.Locale

object CaptionTrackResolver {
    private const val TAG = "CaptionTrackResolver"

    /** Marks a track produced by YouTube's machine translation of another caption track. */
    const val TRANSLATED_PARAM = "tlang"

    private val AUTO_TRANSLATE_TARGETS =
        listOf(
            "en",
            "es",
            "fr",
            "de",
            "pt",
            "it",
            "ru",
            "ja",
            "ko",
            "zh",
            "ar",
            "hi",
            "bn",
            "nl",
            "pl",
            "tr",
            "vi",
            "th",
            "id",
        )

    /**
     * @param preferredLanguage BCP-47 tag the user asked captions to appear in. Translated into
     *   even when it falls outside [AUTO_TRANSLATE_TARGETS], so the preference is always honourable.
     */
    fun resolve(
        playerResponse: PlayerResponse,
        preferredLanguage: String? = null,
    ): List<SubtitlesStream> = resolveTracklist(playerResponse.captions?.playerCaptionsTracklistRenderer, preferredLanguage)

    fun resolveTracklist(
        renderer: PlayerResponse.Captions.PlayerCaptionsTracklistRenderer?,
        preferredLanguage: String? = null,
    ): List<SubtitlesStream> {
        if (renderer == null) return emptyList()
        val tracks =
            renderer.captionTracks
                ?.filter { !it.baseUrl.isNullOrBlank() && !it.languageCode.isNullOrBlank() }
                .orEmpty()
        if (tracks.isEmpty()) return emptyList()

        val result = mutableListOf<SubtitlesStream>()

        tracks.forEach { track ->
            buildStream(track.baseUrl!!, track.languageCode!!, autoGenerated = track.kind == "asr")
                ?.let { result.add(it) }
        }

        val translatableTrack = tracks.firstOrNull { it.isTranslatable == true }
        if (translatableTrack != null) {
            val nativeCodes = tracks.mapNotNull { it.languageCode }.toSet()
            translationTargets(renderer, preferredLanguage)
                .filterNot { target -> nativeCodes.any { it.equals(target, ignoreCase = true) } }
                .forEach { target ->
                    buildStream(
                        translatableTrack.baseUrl!!,
                        target,
                        autoGenerated = true,
                        translateTo = target,
                    )?.let { result.add(it) }
                }
        }

        Log.d(TAG, "Resolved ${result.size} caption tracks (${tracks.size} native) from InnerTube captions")
        return result
    }

    fun isTranslated(stream: SubtitlesStream): Boolean = stream.getContent().contains("&$TRANSLATED_PARAM=")

    private fun translationTargets(
        renderer: PlayerResponse.Captions.PlayerCaptionsTracklistRenderer,
        preferredLanguage: String?,
    ): List<String> {
        val advertised = renderer.translationLanguages?.mapNotNull { it.languageCode }.orEmpty()
        val curated =
            if (advertised.isEmpty()) {
                AUTO_TRANSLATE_TARGETS
            } else {
                AUTO_TRANSLATE_TARGETS.filter { target -> advertised.any { it.equals(target, ignoreCase = true) } }
            }
        val preferred = preferredLanguage?.takeIf { it.isNotBlank() && it != NO_PREFERRED_LANGUAGE }
        return if (preferred != null && curated.none { it.equals(preferred, ignoreCase = true) }) {
            listOf(preferred) + curated
        } else {
            curated
        }
    }

    private fun buildStream(
        baseUrl: String,
        languageCode: String,
        autoGenerated: Boolean,
        translateTo: String? = null,
    ): SubtitlesStream? =
        try {
            SubtitlesStream
                .Builder()
                .setContent(timedTextUrl(baseUrl, translateTo), true)
                .setMediaFormat(MediaFormat.VTT)
                .setLanguageCode(languageCode)
                .setAutoGenerated(autoGenerated)
                .build()
        } catch (e: Exception) {
            Log.w(TAG, "Failed to build SubtitlesStream for $languageCode: ${e.message}")
            null
        }

    private fun timedTextUrl(
        baseUrl: String,
        translateTo: String?,
    ): String {
        val separatorIndex = baseUrl.indexOf('?')
        val path = if (separatorIndex >= 0) baseUrl.substring(0, separatorIndex) else baseUrl
        val query = if (separatorIndex >= 0) baseUrl.substring(separatorIndex + 1) else ""

        val retained =
            query
                .split('&')
                .filter { it.isNotEmpty() && !it.isParam("fmt") && !it.isParam(TRANSLATED_PARAM) }
                .toMutableList()

        retained.add("fmt=vtt")
        translateTo?.takeIf { it.isNotBlank() }?.let { retained.add("$TRANSLATED_PARAM=$it") }

        return "$path?${retained.joinToString("&")}"
    }

    private fun String.isParam(name: String): Boolean = startsWith("$name=", ignoreCase = true) || equals(name, ignoreCase = true)

    const val NO_PREFERRED_LANGUAGE = "none"

    fun <T> bestMatch(
        candidates: List<T>,
        languageTag: String?,
        tagOf: (T) -> String?,
        isAutoGenerated: (T) -> Boolean,
    ): T? {
        val wanted = languageTag?.takeIf { it.isNotBlank() && it != NO_PREFERRED_LANGUAGE } ?: return null
        val wantedBase = baseLanguage(wanted)
        val ranked =
            candidates
                .filter { baseLanguage(tagOf(it).orEmpty()) == wantedBase }
                .sortedWith(
                    compareBy<T> { !tagOf(it).equals(wanted, ignoreCase = true) }
                        .thenBy { isAutoGenerated(it) },
                )
        return ranked.firstOrNull()
    }

    private fun baseLanguage(tag: String): String =
        tag
            .substringBefore('-')
            .substringBefore('_')
            .lowercase(Locale.ROOT)
}
