package io.github.aedev.flow.player.stream

import android.util.Log
import io.github.aedev.flow.player.state.AudioTrackOption
import io.github.aedev.flow.player.state.SubtitleOption
import java.util.Locale
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.extractor.stream.VideoStream

/**
 * Manages stream data processing - deduplication, sorting, and conversion.
 */
object StreamProcessor {
    
    private const val TAG = "StreamProcessor"
    
    /**
     * Process video streams - deduplicate and sort by height descending.
     */
    fun processVideoStreams(streams: List<VideoStream>): List<VideoStream> {
        return streams
            .distinctBy { it.getContent() }
            .sortedWith(
                compareByDescending<VideoStream> { VideoCodecUtils.qualityHeightFromStream(it) }
                    .thenBy { VideoCodecUtils.playbackCodecRank(it) }
                    .thenByDescending { it.bitrate }
            )
            .also { Log.d(TAG, "Processed ${streams.size} video streams -> ${it.size} unique") }
    }
    
    fun processAudioStreams(streams: List<AudioStream>): List<AudioStream> {
        return streams
            .sortedByDescending { it.averageBitrate }
            .groupBy { stream -> extractTrackLanguageKey(stream) }
            .map { (_, group) ->
                group.first()
            }
            .sortedBy { stream -> audioTrackDisplayName(stream).orEmpty() }
            .also { Log.d(TAG, "Processed ${streams.size} audio streams -> ${it.size} unique tracks") }
    }

    fun processSubtitleStreams(streams: List<SubtitlesStream>): List<SubtitlesStream> {
        return streams
            .filter { it.getContent().isNotBlank() }
            .distinctBy { stream ->
                val lang = stream.languageTag ?: stream.locale?.toLanguageTag() ?: stream.getContent()
                "$lang|${stream.isAutoGenerated}"
            }
            .sortedWith(
                compareBy<SubtitlesStream> { it.isAutoGenerated }
                    .thenBy { it.displayLanguageName ?: it.languageTag ?: "" }
            )
            .also { Log.d(TAG, "Processed ${streams.size} subtitle streams -> ${it.size} unique tracks") }
    }

    /**
     * Derive a unique grouping key for deduplication. Uses audioTrackName, audioLocale, or
     * audioTrackId (trying both dot- and underscore-separated suffixes, then full ID) so that
     * tracks with formats like "A_hi" are not all collapsed into a single "default" group.
     */
    private fun extractTrackLanguageKey(stream: AudioStream): String {
        stream.audioTrackName?.takeIf { it.isNotBlank() }?.let { return it }
        stream.audioLocale?.language?.takeIf { it.isNotBlank() }?.let { return it }
        stream.audioTrackId?.let { id ->
            val dotPart = id.substringAfterLast(".").takeIf { it.isNotBlank() && it != id }
            if (dotPart != null) return dotPart
            val underPart = id.substringAfterLast("_").takeIf { it.isNotBlank() && it != id }
            if (underPart != null) return underPart
            return id
        }
        return "default"
    }

    /**
     * Derive a human-readable language display name from an AudioStream.
     * Priority: audioTrackName → audioLocale display language → parsed audioTrackId → fallback.
     */
    fun audioTrackDisplayName(stream: AudioStream): String? {
        stream.audioTrackName?.takeIf { it.isNotBlank() }?.let { return it }

        stream.audioLocale?.language?.takeIf { it.isNotBlank() }?.let { langCode ->
            localizedLanguageName(langCode)?.let { return it }
        }

        stream.audioTrackId?.let { trackId ->
            val dotCode = trackId.substringAfterLast(".").takeIf { it.isNotBlank() && it != trackId }
            val underCode = trackId.substringAfterLast("_").takeIf { it.isNotBlank() && it != trackId }
            val langCode = dotCode ?: underCode
            if (langCode != null) {
                localizedLanguageName(langCode)?.let { return it }
            }
            return trackId.replaceFirstChar { it.uppercase() }
        }

        return null
    }
    
    /**
     * Convert audio streams to UI options.
     */
    fun toAudioTrackOptions(streams: List<AudioStream>): List<AudioTrackOption> {
        return streams.mapIndexed { index, stream ->
            AudioTrackOption(
                index = index,
                label = audioTrackDisplayName(stream).orEmpty(),
                language = stream.audioLocale?.displayLanguage
                    ?.takeIf { it.isNotBlank() }
                    ?: "",
                bitrate = stream.averageBitrate.coerceAtLeast(0).toLong()
            )
        }
    }
    
    /**
     * Convert subtitle streams to UI options.
     */
    fun toSubtitleOptions(subtitles: List<SubtitlesStream>): List<SubtitleOption> {
        return subtitles.map {
            val language = it.languageTag ?: it.locale?.toLanguageTag() ?: "Unknown"
            val baseLabel = localizedLanguageName(language)
                ?: it.displayLanguageName
                ?: language
            SubtitleOption(
                url = it.getContent(),
                language = language,
                label = baseLabel,
                isAutoGenerated = it.isAutoGenerated
            )
        }
    }

    private fun localizedLanguageName(languageTag: String): String? {
        val languageLocale = Locale.forLanguageTag(languageTag.replace('_', '-'))
        val languageCode = languageLocale.language.takeIf { it.isNotBlank() } ?: return null
        val displayLocale = Locale.getDefault()
        val displayName = languageLocale.getDisplayLanguage(displayLocale)
        if (displayName.isBlank() || displayName.equals(languageCode, ignoreCase = true)) return null
        return displayName.replaceFirstChar { character ->
            if (character.isLowerCase()) character.titlecase(displayLocale) else character.toString()
        }
    }
}
