package io.github.aedev.flow.data.sponsordetection

import com.google.common.truth.Truth.assertThat
import kotlinx.coroutines.test.runTest
import org.junit.Test
import java.io.ByteArrayOutputStream
import java.nio.file.Files

class SponsorFeedbackFileStoreTest {
    @Test
    fun `evaluation is deduplicated and feedback remains append only`() =
        runTest {
            val directory = Files.createTempDirectory("sponsor-feedback").toFile()
            val store = SponsorFeedbackFileStore(directory.resolve("feedback.jsonl"))

            assertThat(store.recordEvaluation(evaluation())).isTrue()
            assertThat(store.recordEvaluation(evaluation())).isFalse()
            assertThat(
                store.recordFeedback(
                    SponsorFeedbackEvent(
                        feedbackId = "feedback-1",
                        evaluationId = "evaluation-1",
                        createdAtEpochMs = 2,
                        targetSpanId = "prediction-1",
                        verdict = SponsorFeedbackVerdict.ACCEPTED,
                        originalSpan = SponsorSpan(1_000, 2_000),
                    ),
                ),
            ).isTrue()

            val output = ByteArrayOutputStream()
            store.exportTo(output)
            val lines = output.toString(Charsets.UTF_8.name()).lines().filter(String::isNotBlank)
            assertThat(lines).hasSize(2)
            assertThat(lines.first()).contains("\"event_type\":\"evaluation\"")
            assertThat(lines.last()).contains("\"event_type\":\"feedback\"")
            assertThat(store.stats.value.evaluationCount).isEqualTo(1)
            assertThat(store.stats.value.feedbackCount).isEqualTo(1)
            assertThat(store.recordEvaluation(evaluation())).isFalse()
        }

    @Test
    fun `export does not clear journal records`() =
        runTest {
            val directory = Files.createTempDirectory("sponsor-feedback-export").toFile()
            val store = SponsorFeedbackFileStore(directory.resolve("feedback.jsonl"))
            store.recordEvaluation(evaluation())

            val output = ByteArrayOutputStream()
            store.exportTo(output)

            assertThat(output.toString(Charsets.UTF_8.name())).contains("evaluation")
            assertThat(store.stats.value.evaluationCount).isEqualTo(1)
            assertThat(store.recordEvaluation(evaluation())).isFalse()
        }

    @Test
    fun `clear resets journal and dedupe index`() =
        runTest {
            val directory = Files.createTempDirectory("sponsor-feedback-clear").toFile()
            val store = SponsorFeedbackFileStore(directory.resolve("feedback.jsonl"))
            store.recordEvaluation(evaluation())

            store.clear()

            assertThat(store.stats.value).isEqualTo(SponsorJournalStats())
            assertThat(store.recordEvaluation(evaluation())).isTrue()
        }

    @Test
    fun `size limit pauses writes without deleting existing records`() =
        runTest {
            val directory = Files.createTempDirectory("sponsor-feedback-limit").toFile()
            val journal = directory.resolve("feedback.jsonl")
            val store = SponsorFeedbackFileStore(journal = journal, maxBytes = 4_096)

            assertThat(store.recordEvaluation(evaluation())).isTrue()
            val sizeAfterFirst = journal.length()
            val limited = SponsorFeedbackFileStore(journal = journal, maxBytes = sizeAfterFirst + 8)

            assertThat(limited.recordFeedback(feedback())).isFalse()
            assertThat(journal.length()).isEqualTo(sizeAfterFirst)
            assertThat(limited.stats.value.isFull).isTrue()
            assertThat(limited.stats.value.evaluationCount).isEqualTo(1)
        }

    private fun evaluation() =
        SponsorEvaluationEvent(
            evaluationId = "evaluation-1",
            dedupeKey = "dedupe-1",
            createdAtEpochMs = 1,
            videoId = "video-1",
            modelName = SPONSOR_MODEL_NAME,
            modelSha256 = SPONSOR_MODEL_SHA256,
            tokenizerSha256 = SPONSOR_TOKENIZER_SHA256,
            transcriptSha256 = "a".repeat(64),
            languageTag = "en",
            transcriptSource = SponsorTranscriptSource.YOUTUBE,
            isAutoGenerated = false,
            apiOutcome = SponsorApiOutcome.EMPTY,
            apiSpans = emptyList(),
            predictions = listOf(SponsorPredictedSpan("prediction-1", 1_000, 2_000, 0.9)),
            comparison = SponsorComparison(emptyList(), listOf("prediction-1"), emptyList()),
            transcriptWindows =
                listOf(
                    SponsorTranscriptWindow(
                        kind = SponsorTranscriptWindowKind.SEGMENT_CONTEXT,
                        startMs = 0,
                        endMs = 3_000,
                        cues = listOf(SponsorTranscriptCue(0, 3_000, "A sponsor cue")),
                    ),
                ),
            inferenceMs = 10,
        )

    private fun feedback() =
        SponsorFeedbackEvent(
            feedbackId = "feedback-2",
            evaluationId = "evaluation-1",
            createdAtEpochMs = 3,
            targetSpanId = "prediction-1",
            verdict = SponsorFeedbackVerdict.REJECTED,
            originalSpan = SponsorSpan(1_000, 2_000),
        )
}
