package com.flow.youtube.player.stream

import android.util.Log
import com.flow.youtube.player.state.AudioTrackOption
import com.flow.youtube.player.state.SubtitleOption
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.extractor.stream.VideoStream

/**
 * Manages stream data processing - deduplication, sorting, and conversion.
 */
object StreamProcessor {
    
    private const val TAG = "StreamProcessor"
    
    /**
     * Process video streams - deduplicate and sort by height descending.
     */
    fun processVideoStreams(streams: List<VideoStream>): List<VideoStream> {
        return streams
            .distinctBy { it.getContent() }
            .sortedByDescending { it.height }
            .also { Log.d(TAG, "Processed ${streams.size} video streams -> ${it.size} unique") }
    }
    
    fun processAudioStreams(streams: List<AudioStream>): List<AudioStream> {
        return streams
            .sortedByDescending { it.averageBitrate }
            .groupBy { stream ->
                val trackIdLang = stream.audioTrackId
                    ?.substringAfterLast(".")
                    ?.takeIf { it.isNotBlank() && it != stream.audioTrackId }
                val localeLang = stream.audioLocale?.language?.takeIf { it.isNotBlank() }
                val trackName = stream.audioTrackName?.takeIf { it.isNotBlank() }
                trackIdLang ?: localeLang ?: trackName ?: "default"
            }
            .map { (_, group) ->
                group.first()
            }
            .sortedBy { stream -> languageDisplayName(stream, 0) }
            .also { Log.d(TAG, "Processed ${streams.size} audio streams -> ${it.size} unique tracks") }
    }

    /**
     * Derive a human-readable language display name from an AudioStream.
     * Priority: audioTrackName → audioLocale display language → parsed audioTrackId → fallback.
     */
    private fun languageDisplayName(stream: AudioStream, fallbackIndex: Int): String {
        stream.audioTrackName?.takeIf { it.isNotBlank() }?.let { return it }

        stream.audioLocale?.language?.takeIf { it.isNotBlank() }?.let { langCode ->
            val locale = java.util.Locale(langCode)
            val name = locale.getDisplayLanguage(java.util.Locale.getDefault())
            if (name.isNotBlank()) return name.replaceFirstChar { it.uppercase() }
        }

        stream.audioTrackId?.let { trackId ->
            val langCode = trackId.substringAfterLast(".").takeIf {
                it.isNotBlank() && it != trackId
            }
            if (langCode != null) {
                val locale = java.util.Locale(langCode)
                val name = locale.getDisplayLanguage(java.util.Locale.getDefault())
                if (name.isNotBlank() && !name.equals(langCode, ignoreCase = true)) {
                    return name.replaceFirstChar { it.uppercase() }
                }
            }
            return trackId.replaceFirstChar { it.uppercase() }
        }

        return "Track ${fallbackIndex + 1}"
    }
    
    /**
     * Convert audio streams to UI options.
     */
    fun toAudioTrackOptions(streams: List<AudioStream>): List<AudioTrackOption> {
        return streams.mapIndexed { index, stream ->
            AudioTrackOption(
                index = index,
                label = languageDisplayName(stream, index),
                language = stream.audioLocale?.displayLanguage
                    ?.takeIf { it.isNotBlank() }
                    ?: "",
                bitrate = stream.averageBitrate.coerceAtLeast(0).toLong()
            )
        }
    }
    
    /**
     * Convert subtitle streams to UI options.
     */
    fun toSubtitleOptions(subtitles: List<SubtitlesStream>): List<SubtitleOption> {
        return subtitles.map {
            SubtitleOption(
                url = it.getContent(),
                language = it.languageTag ?: "Unknown",
                label = it.displayLanguageName ?: it.languageTag ?: "Unknown",
                isAutoGenerated = it.isAutoGenerated
            )
        }
    }
}
