package com.flow.youtube.player.stream

import android.util.Log
import com.flow.youtube.player.state.AudioTrackOption
import com.flow.youtube.player.state.SubtitleOption
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.extractor.stream.VideoStream

/**
 * Manages stream data processing - deduplication, sorting, and conversion.
 */
object StreamProcessor {
    
    private const val TAG = "StreamProcessor"
    
    /**
     * Process video streams - deduplicate and sort by height descending.
     */
    fun processVideoStreams(streams: List<VideoStream>): List<VideoStream> {
        return streams
            .distinctBy { it.getContent() }
            .sortedByDescending { it.height }
            .also { Log.d(TAG, "Processed ${streams.size} video streams -> ${it.size} unique") }
    }
    
    /**
     * Process audio streams - deduplicate by track ID and sort alphabetically.
     */
    fun processAudioStreams(streams: List<AudioStream>): List<AudioStream> {
        return streams
            .sortedByDescending { it.averageBitrate } // Put highest quality first
            .distinctBy { 
                // Unique key for the TRACK 
                "${it.audioTrackId ?: "none"}_${it.audioTrackName ?: "none"}_${it.audioLocale?.language ?: "none"}"
            }
            .sortedBy { it.audioTrackName ?: "" } // Sort alphabetically for the menu
            .also { Log.d(TAG, "Processed ${streams.size} audio streams -> ${it.size} unique tracks") }
    }
    
    /**
     * Convert audio streams to UI options.
     */
    fun toAudioTrackOptions(streams: List<AudioStream>): List<AudioTrackOption> {
        return streams.mapIndexed { index, stream ->
            AudioTrackOption(
                index = index,
                label = stream.audioTrackName ?: stream.audioTrackId ?: "Track ${index + 1}",
                language = stream.audioLocale?.displayLanguage ?: "Unknown",
                bitrate = stream.averageBitrate.toLong()
            )
        }
    }
    
    /**
     * Convert subtitle streams to UI options.
     */
    fun toSubtitleOptions(subtitles: List<SubtitlesStream>): List<SubtitleOption> {
        return subtitles.map {
            SubtitleOption(
                url = it.getContent(),
                language = it.languageTag ?: "Unknown",
                label = it.displayLanguageName ?: it.languageTag ?: "Unknown",
                isAutoGenerated = it.isAutoGenerated
            )
        }
    }
}
