package io.github.aedev.flow.player.stream

import io.github.aedev.flow.innertube.models.response.PlayerResponse
import io.github.aedev.flow.player.state.SubtitleOption
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.schabi.newpipe.extractor.MediaFormat

/** A signed timedtext URL as YouTube serves it today — note the trailing `fmt=srv3`. */
private const val BASE_URL =
    "https://www.youtube.com/api/timedtext?v=abc&ei=XYZ&caps=asr&sparams=ip,ipbits,expire,v" +
        "&signature=DEADBEEF.0123&key=yt8&lang=en&fmt=srv3"

private fun tracklist(
    tracks: List<PlayerResponse.Captions.CaptionTrack>,
    translationLanguages: List<String>? = null,
) = PlayerResponse.Captions.PlayerCaptionsTracklistRenderer(
    captionTracks = tracks,
    translationLanguages =
        translationLanguages?.map {
            PlayerResponse.Captions.TranslationLanguage(languageCode = it)
        },
)

private fun track(
    languageCode: String,
    kind: String? = null,
    translatable: Boolean = false,
    baseUrl: String = BASE_URL,
) = PlayerResponse.Captions.CaptionTrack(
    baseUrl = baseUrl,
    languageCode = languageCode,
    kind = kind,
    isTranslatable = translatable,
)

class CaptionTrackResolverTest {
    @Test
    fun `srv3 is requested by default for styled and positioned captions`() {
        val resolved = CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en"))))

        val url = resolved.single().getContent()
        assertEquals("exactly one fmt parameter expected: $url", 1, url.split("fmt=").size - 1)
        assertTrue(url.endsWith("fmt=srv3"))
    }

    @Test
    fun `an explicit vtt format request is honoured, not duplicated`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en"))), format = MediaFormat.VTT)

        val url = resolved.single().getContent()
        assertFalse("srv3 must not survive: $url", url.contains("fmt=srv3"))
        assertEquals("exactly one fmt parameter expected: $url", 1, url.split("fmt=").size - 1)
        assertTrue(url.endsWith("fmt=vtt"))
    }

    @Test
    fun `signed parameters survive untouched so the url stays valid`() {
        val url = CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en")))).single().getContent()

        assertTrue(url.contains("signature=DEADBEEF.0123"))
        assertTrue("commas in sparams must not be re-encoded: $url", url.contains("sparams=ip,ipbits,expire,v"))
        assertTrue(url.startsWith("https://www.youtube.com/api/timedtext?"))
    }

    @Test
    fun `a translation is offered even when the client sends no translation languages`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(
                tracklist(listOf(track("en", translatable = true))),
                preferredLanguage = "es",
            )

        val spanish = resolved.single { it.languageTag == "es" }
        assertTrue(spanish.getContent().contains("tlang=es"))
        assertTrue(CaptionTrackResolver.isTranslated(spanish))
        assertFalse(CaptionTrackResolver.isTranslated(resolved.first { it.languageTag == "en" }))
    }

    @Test
    fun `a preferred language outside the curated set still gets a translation`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(
                tracklist(listOf(track("en", translatable = true))),
                preferredLanguage = "sw",
            )

        assertTrue(resolved.any { it.languageTag == "sw" && CaptionTrackResolver.isTranslated(it) })
    }

    @Test
    fun `languages the video already has are never offered as translations`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(
                tracklist(listOf(track("en", translatable = true), track("de"))),
                preferredLanguage = "de",
            )

        assertEquals(1, resolved.count { it.languageTag == "de" })
        assertFalse(CaptionTrackResolver.isTranslated(resolved.single { it.languageTag == "de" }))
    }

    @Test
    fun `an advertised translation list narrows the targets`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(
                tracklist(listOf(track("en", translatable = true)), translationLanguages = listOf("fr")),
            )

        val translated = resolved.filter { CaptionTrackResolver.isTranslated(it) }
        assertEquals(listOf("fr"), translated.map { it.languageTag })
    }

    @Test
    fun `a stored region tag still matches the base language and prefers the human track`() {
        val options =
            listOf(
                SubtitleOption(url = "a", language = "pt-BR", label = "Portuguese", isAutoGenerated = true),
                SubtitleOption(url = "b", language = "pt-BR", label = "Portuguese", isAutoGenerated = false),
                SubtitleOption(url = "c", language = "en", label = "English", isAutoGenerated = false),
            )

        val match =
            CaptionTrackResolver.bestMatch(
                candidates = options,
                languageTag = "pt",
                tagOf = { it.language },
                isAutoGenerated = { it.isAutoGenerated },
            )

        assertEquals("b", match?.url)
    }

    @Test
    fun `no preference matches nothing`() {
        val options = listOf(SubtitleOption(url = "a", language = "en", label = "English", isAutoGenerated = false))

        assertNull(
            CaptionTrackResolver.bestMatch(
                candidates = options,
                languageTag = CaptionTrackResolver.NO_PREFERRED_LANGUAGE,
                tagOf = { it.language },
                isAutoGenerated = { it.isAutoGenerated },
            ),
        )
    }
}
